-- =====================================================
-- Masterserver Plugin - Daemon Instances Table
-- =====================================================
-- Stores registered daemons per guild (1:1 relationship)
-- Each guild can have exactly ONE daemon
-- Daemon connects via WebSocket and sends heartbeats
-- =====================================================

CREATE TABLE IF NOT EXISTS daemon_instances (
    -- Primary Key
    id INT AUTO_INCREMENT PRIMARY KEY,
    
    -- Unique Identifiers
    daemon_id VARCHAR(36) UNIQUE NOT NULL COMMENT 'UUID generated by daemon on first start',
    guild_id VARCHAR(30) NOT NULL COMMENT 'Discord Guild ID (1:1 relationship)',
    
    -- Display Info
    display_name VARCHAR(100) DEFAULT NULL COMMENT 'User-defined display name for this daemon',
    
    -- Connection Info
    host_ip VARCHAR(45) DEFAULT NULL COMMENT 'Daemon IP address (IPv4/IPv6)',
    host_port INT DEFAULT NULL COMMENT 'WebSocket port on daemon side (if applicable)',
    
    -- Authentication
    session_token TEXT DEFAULT NULL COMMENT 'Rotating session token for ongoing communication',
    session_token_expires_at TIMESTAMP NULL DEFAULT NULL COMMENT 'Session token expiration',
    
    -- Status
    status ENUM('online', 'offline', 'error', 'maintenance') DEFAULT 'offline' COMMENT 'Current daemon status',
    version VARCHAR(20) DEFAULT NULL COMMENT 'Daemon version (e.g. 1.0.0)',
    os_info VARCHAR(255) DEFAULT NULL COMMENT 'Operating system info (e.g. Ubuntu 22.04 LTS)',
    
    -- Heartbeat Monitoring
    last_heartbeat TIMESTAMP NULL DEFAULT NULL COMMENT 'Last successful heartbeat received',
    last_ping_latency INT DEFAULT NULL COMMENT 'Last ping latency in milliseconds',
    missed_heartbeats INT DEFAULT 0 COMMENT 'Counter for missed heartbeats (reset on success)',
    
    -- Statistics
    total_commands INT DEFAULT 0 COMMENT 'Total commands sent to this daemon',
    total_uptime_seconds BIGINT DEFAULT 0 COMMENT 'Total uptime in seconds (accumulated)',
    
    -- Timestamps
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'First registration timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
    last_disconnect TIMESTAMP NULL DEFAULT NULL COMMENT 'Last disconnect timestamp',
    
    -- Constraints
    UNIQUE KEY unique_guild_daemon (guild_id) COMMENT 'Enforce 1:1 guild-daemon relationship',
    INDEX idx_guild (guild_id),
    INDEX idx_status (status),
    INDEX idx_heartbeat (last_heartbeat),
    INDEX idx_daemon (daemon_id)
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Registered daemon instances (1 per guild)';
