CREATE TABLE IF NOT EXISTS ticket_categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    guild_id VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT DEFAULT NULL,
    parent_id VARCHAR(20) DEFAULT NULL COMMENT 'Discord Category ID (null = auto-create)',
    channel_style ENUM('NUMBER', 'NAME', 'ID') DEFAULT 'NUMBER',
    staff_roles JSON DEFAULT NULL COMMENT '["roleId1","roleId2"]',
    member_roles JSON DEFAULT NULL COMMENT '["roleId1"]',
    open_msg_title VARCHAR(256) DEFAULT NULL,
    open_msg_description TEXT DEFAULT NULL,
    open_msg_footer VARCHAR(256) DEFAULT NULL,
    button_label VARCHAR(80) DEFAULT 'Ticket erstellen',
    button_emoji VARCHAR(50) DEFAULT '🎫',
    button_color ENUM('PRIMARY', 'SECONDARY', 'SUCCESS', 'DANGER') DEFAULT 'PRIMARY',
    max_open_per_user INT UNSIGNED DEFAULT 1,
    form_fields JSON DEFAULT NULL COMMENT '[{"label":"Betreff","placeholder":"...","style":"SHORT","required":true}]',
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_guild_name (guild_id, name),
    INDEX idx_guild (guild_id),
    INDEX idx_guild_active (guild_id, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
