CREATE TABLE IF NOT EXISTS `ticket_auto_responses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guild_id` VARCHAR(20) NOT NULL,
  `keywords` JSON NOT NULL,
  `response` TEXT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_guild_active` (`guild_id`, `is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
