CREATE TABLE IF NOT EXISTS tickets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    guild_id VARCHAR(20) NOT NULL,
    category_id INT UNSIGNED DEFAULT NULL,
    channel_id VARCHAR(20) NOT NULL,
    ticket_id VARCHAR(20) NOT NULL COMMENT 'Unique short ID (z.B. aB3xK9mQ)',
    ticket_number INT UNSIGNED NOT NULL,
    created_by VARCHAR(20) NOT NULL,
    claimed_by VARCHAR(20) DEFAULT NULL,
    claimed_at TIMESTAMP NULL DEFAULT NULL,
    status ENUM('open', 'closed') DEFAULT 'open',
    close_reason TEXT DEFAULT NULL,
    closed_by VARCHAR(20) DEFAULT NULL,
    category_name VARCHAR(100) DEFAULT NULL COMMENT 'Denormalized for log display',
    form_responses JSON DEFAULT NULL COMMENT '[{"label":"Betreff","value":"answer"}]',
    opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP NULL DEFAULT NULL,
    reopened_by VARCHAR(20) DEFAULT NULL,
    reopened_at TIMESTAMP NULL DEFAULT NULL,
    reopen_count INT UNSIGNED DEFAULT 0,
    UNIQUE KEY uk_guild_ticket_id (guild_id, ticket_id),
    INDEX idx_guild (guild_id),
    INDEX idx_guild_status (guild_id, status),
    INDEX idx_guild_user (guild_id, created_by),
    INDEX idx_channel (channel_id),
    CONSTRAINT fk_ticket_category FOREIGN KEY (category_id) 
        REFERENCES ticket_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
