CREATE TABLE IF NOT EXISTS ticket_settings (
    guild_id VARCHAR(20) NOT NULL PRIMARY KEY,
    log_channel VARCHAR(20) DEFAULT NULL,
    ticket_limit INT UNSIGNED DEFAULT 10,
    embed_color_create VARCHAR(7) DEFAULT '#068ADD',
    embed_color_close VARCHAR(7) DEFAULT '#068ADD',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
